<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Subsektor_model extends CI_Model
{

    public $table = 'subsektor';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('id_sektor DESC, name ASC');
        return $this->db->get($this->table)->result();
    }

    function grid()
    {
        $this->load->database();
        $this->load->library("datatables");
        $this->datatables->select('a.id, b.name as sektor, a.name', false)
            ->from('subsektor a')
            ->join('sektor b','b.id = a.id_sektor')
            ->add_column('action','<a class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit" href="'.site_url().'cms/subsektor/update/$1"><i class="fa fa-edit"></i></a> <button onclick="return confirmModal(\''.base_url().'cms/subsektor/delete/$1\')" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>','id');
        return $this->datatables->generate();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    public function select_dropdown_subsektor($id)
    {
        $return = array();
        if($id)
        {
            $this->db->select("*");
            $this->db->from($this->table);
            $this->db->where('id_sektor', $id);
            $this->db->order_by('name','ASC');
            $rs = $this->db->get();
            $data = $rs->result_array();
            if(count($data)>0){
                $return[] = '-- Pilih --';
                foreach($data as $row){
                    $return[$row['id']] = ucfirst($row['name']);
                }
            }
        } else {
            $return[] = '-- Pilih --';
        }
        return $return;
    }

    function get_category_select($init = array())
    {
        $tmp = array();
        if(is_array($init) AND count($init)>0) $tmp = $init;
        $this->db->select("*");
        $this->db->from($this->table);
        $this->db->order_by('name','ASC');
        $rs = $this->db->get();
        $data = $rs->result_array();
        if(count($data)>0){
            foreach($data as $row){
                $tmp[$row['id']] = ucfirst($row['name']);
            }
        }
        return $tmp;
    }

    public function get_list_subsektor($id){
        $this->db->where('id_sektor', $id);
        return $this->db->get($this->table)->result_array();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Subsektor_model.php */
/* Location: ./application/models/Subsektor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-16 03:29:41 */
/* http://harviacode.com */